datauser/urls.py
from django.urls import path
from .views import AcademyDetailView, AcademyCreateView, AcademyUpdateView, AcademyDeleteView, SkillsCreateView, SkillsUpdateView, SkillsDeleteView, HistoryCreateView, HistoryUpdateView, HistoryDeleteView, ProjectCreateView, ProjectUpdateView, ProjectDeleteView, StackCreateView, FactsCreateView, FactsUpdateView, FactsDeleteView, get_job_data

urlpatterns =[
    path('academy/<int:pk>/', AcademyDetailView.as_view(), name= 'academy-detail'),
    path('academy-add/', AcademyCreateView.as_view(), name= 'academy-create'),
    path('academy-upd/<int:pk>/', AcademyUpdateView.as_view(), name= 'academy-update'),
    path('academy-del/<int:pk>/', AcademyDeleteView.as_view(), name= 'academy-delete'),
    path('skills-add/', SkillsCreateView.as_view(), name= 'skills-create'),
    path('skills-upd/<int:pk>/', SkillsUpdateView.as_view(), name= 'skills-update'),
    path('skills-del/<int:pk>/', SkillsDeleteView.as_view(), name= 'skills-delete'),
    path('history-add/', HistoryCreateView.as_view(), name= 'history-create'),
    path('history-upd/<int:pk>/', HistoryUpdateView.as_view(), name= 'history-update'),
    path('history-del/<int:pk>/', HistoryDeleteView.as_view(), name= 'history-delete'),
    path('project-add/', ProjectCreateView.as_view(), name= 'project-create'),
    path('project-upd/<int:pk>/', ProjectUpdateView.as_view(), name= 'project-update'),
    path('project-del/<int:pk>/', ProjectDeleteView.as_view(), name= 'project-delete'),
    path('stack-add/', StackCreateView.as_view(), name= 'stack-create'),
    path('fact-add/', FactsCreateView.as_view(), name= 'fact-create'),
    path('fact-upd/<int:pk>/', FactsUpdateView.as_view(), name= 'fact-update'),
    path('fact-del/<int:pk>/', FactsDeleteView.as_view(), name= 'fact-delete'),
    path('api/job-data/', get_job_data, name='get_job_data'),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
# Opciones para ver imagenes:
from django.conf import settings
from django.conf.urls.static import static
from messenger.urls import messenger_patterns

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('core.urls')),
    # Para implementar el login
    path('accounts/', include('django.contrib.auth.urls') ),
    # datauser:
    path('users/',include('datauser.urls')),
    # registration
    path('user/',include('registration.urls')),
    # perfiles
    path('users/',include('perfiles.urls')),
    # contacto:
    path('users/contacto', include('contacto.urls')),
    # messenger:
    path('chat/', include(messenger_patterns)),
    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

datauser/models.py
from django.db import models
from registration.models import User
# Importamos la libreria de texto enriquecido:
from ckeditor.fields import RichTextField

# Create your models here.
class Stack(models.Model):
    name_stack =  models.CharField(verbose_name='Nombre de Stack', max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Stack"
        verbose_name_plural = "Tecnicas Usadas"

    def __str__(self):
        return f'{self.name_stack}'
    
class ProjectDev(models.Model):
    user = models.ForeignKey(User , on_delete=models.CASCADE )
    stack = models.ManyToManyField(Stack, verbose_name="Tecnologias Usadas")
    name_project = models.CharField(verbose_name='Nombre de Proyecto', max_length=100)
    resume_project = models.TextField(verbose_name='Descripcion')
    url_repo = models.URLField(verbose_name='Url Repositorio')
    year_production = models.PositiveIntegerField(verbose_name='Año en Producción', null=True, blank=True)
    developing = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Proyectos Desarrollados'

    def __str__(self) :
        return f'{self.name_project}'
    
class EmploymentHistory(models.Model):
    user = models.ForeignKey(User , on_delete=models.CASCADE )
    stack = models.ManyToManyField(Stack, verbose_name="Tecnologias Usadas")
    company = models.CharField(verbose_name='Empresa',max_length=256)
    position = models.CharField(verbose_name='Cargo', max_length=150)
    job_description = RichTextField(verbose_name='Funciones Desempeñadas')
    start_date = models.DateField(verbose_name='Fecha de Inicio')
    end_date = models.DateField(verbose_name='Fecha de Culminación', null=True, blank=True)
    still_work = models.BooleanField(default=False, verbose_name='Aún trabajo allí')
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Historia Laboral'

    def __str__(self):
        return f'{self.company} - {self.position}'
    
class Academy(models.Model):
    ESTUDIOS = [
        ("Primaria","Primaria"),
        ("Bachillerato","Bachillerato"),
        ("Curso","Curso"),
        ("Tecnico","Tecnico"),
        ("Tecnologo", "Tecnologo"),
        ("Pregrado","Pregrado"),
        ("Posgrado", "Posgrado"),
    ]
    user = models.ForeignKey(User , on_delete=models.CASCADE )
    type_degree = models.CharField(verbose_name='Tipo de Educación', choices=ESTUDIOS, max_length=150)
    academy_name = models.CharField(verbose_name='Institución Educativa', max_length=150)
    degree_obtained = models.CharField(verbose_name='Grado Obtenido',  max_length=50)
    degree_esp = models.CharField(verbose_name='Especialidad del Grado',  max_length=50, null=True, blank=True)
    start_date = models.DateField(verbose_name='Fecha de Inicio de Estudios', null=True, blank=True)
    finish_date = models.DateField(verbose_name='Fecha de Graduación', null=True, blank=True)
    in_progress = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "Formacion Académica"

    def __str__(self) -> str:
        if self.finish_date is None:
            return f'{self.degree_obtained} - en Progreso'
        else:
            return f'{self.degree_obtained} - {self.finish_date}'
        
class HobbiesExtras(models.Model):
    user = models.ForeignKey(User , on_delete=models.CASCADE )
    hobby = models.CharField(verbose_name='Afición/Pasatiempo', max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Hobbies - Extras'

    def __str__(self):
        return f'{self.hobby}'
    
class Skills(models.Model):
    LEVEL = [
        ('Basico','Basico'),
        ('Intermedio','Intermedio'),
        ('Alto','Alto'),
        ('Avanzado','Avanzado')
    ]
    user = models.ForeignKey(User , on_delete=models.CASCADE )
    skill = models.CharField(verbose_name='Competencias', max_length=100)
    level = models.CharField(verbose_name='Nivel', choices=LEVEL, max_length=100)
    description = models.TextField(verbose_name='Descripcion') #descripcion detallada del nivel y habilidades adquiridas
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Habilidades'

    def __str__(self):
        return f'{self.skill} - {self.level}'
    

class Facts(models.Model):
    TYPE_FACT=[
        ('Clientes','Clientes'),
        ('Proyectos','Proyectos'),
        ('Horas de Soporte','Horas de Soporte'),
        ('Hard Workers','Hard Workers'),
    ]
    user = models.ForeignKey(User , on_delete=models.CASCADE)
    fact = models.CharField(verbose_name='Hechos', max_length=25, choices=TYPE_FACT)
    value = models.PositiveIntegerField(verbose_name='Total')
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Hechos'

    def __str__(self):
        return f'{self.fact}'

datauser/forms.py
from django import forms
from .models import Academy, Skills, EmploymentHistory, ProjectDev, Stack, Facts


class AcademyCreateForm(forms.ModelForm):
    class Meta:
        model = Academy
        fields = ['type_degree','academy_name','degree_obtained','degree_esp','start_date','finish_date','in_progress']
        widgets = {
            'type_degree': forms.Select(attrs={'class':'form-select'}),
            'academy_name': forms.TextInput(attrs={'class':'form-control'}),
            'degree_obtained': forms.TextInput(attrs={'class':'form-control'}),
            'degree_esp': forms.TextInput(attrs={'class':'form-control'}),
            'start_date': forms.DateInput(attrs={'class':'form-control'}),
            'finish_date': forms.DateInput(attrs={'class':'form-control'}),
            'in_progress': forms.CheckboxInput(attrs={'class':'form-check-input'}),
        }


class SkillsCreateForm(forms.ModelForm):
    class Meta:
        model = Skills
        fields = ['skill','level','description']
        widgets = {
            'skill': forms.TextInput(attrs={'class':'form-control'}),
            'level': forms.Select(attrs={'class':'form-select'}),
            'description': forms.Textarea(attrs={'class':'form-control', 'rows':5})
        }

class HistoryCreateForm(forms.ModelForm):
    class Meta:
        model = EmploymentHistory
        fields = ['stack','company','position','job_description','start_date','end_date','still_work']
        widgets = {
            'stack': forms.SelectMultiple(attrs={'class':'form-select'}),
            'company': forms.TextInput(attrs={'class':'form-control'}),
            'position': forms.TextInput(attrs={'class':'form-control'}),
            'job_description': forms.Textarea(attrs={'class':'form-control', 'rows':'3'}),
            'start_date': forms.TextInput(attrs={'class':'form-control', 'type':'date'}),
            'end_date': forms.TextInput(attrs={'class':'form-control', 'type':'date'}),
            'still_work': forms.CheckboxInput(attrs={'class':'form-check-input'}),
        }

class ProjectCreateForm(forms.ModelForm):
    class Meta:
        model = ProjectDev
        fields = ['stack','name_project','resume_project','url_repo','year_production','developing']
        widgets = {
            'stack': forms.SelectMultiple(attrs={'class':'form-select'}),
            'name_project': forms.TextInput(attrs={'class':'form-control'}),
            'resume_project': forms.Textarea(attrs={'class':'form-control', 'rows':'3'}),
            'url_repo': forms.TextInput(attrs={'class':'form-control', 'type':'url'}),
            'year_production': forms.NumberInput(attrs={'class':'form-control'}),
            'developing': forms.CheckboxInput(attrs={'class':'form-check-input'})
        }

class StackCreateForm(forms.ModelForm):
    class Meta:
        model = Stack
        fields = ['name_stack',]
        widgets = {
            'name_stack': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Python, Django, MERN'})
        }

class FactsCreateForm(forms.ModelForm):
    class Meta:
        model = Facts
        fields = ['fact','value']
        widgets = {
            'fact': forms.Select(attrs={'class':'form-select'}),
            'value': forms.NumberInput(attrs={'class':'form-control'})
        }

templates/datauser/academy_form.html
{% extends 'core/base.html' %}
{% block titulo %}Academia{% endblock %}
{% load static %}

{% block estilo %}
<link rel="stylesheet" href="{% static 'css/custom.css' %}">
{% endblock %}
{% block contenido %}
    {% include 'core/menu.html' %}
   
    <!-- Modal -->
    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <form method="post">
            <div class="modal-header">
                <h1 class="modal-title fs-5 h3" id="exampleModalLabel">Agregar Registros Académicos</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <section class="container mt-3 row">          
                        {% csrf_token %}
                        <div class="mb-3 col-6">
                            <label for="id_type_degree">Tipo de Educación</label>
                            {{ form.type_degree }}
                        </div>
                        <div class="mb-3 col-6">
                            <label for="id_academy_name">Institución Educativa</label>
                            {{ form.academy_name }}
                        </div>
                        <div class="mb-3 col-12">
                            <label for="id_degree_obtained">Grado Obtenido</label>
                            {{ form.degree_obtained }}
                        </div>
                        <div class="mb-3 col-12">
                            <label for="id_degree_esp">Especialidad del Grado</label>
                            {{ form.degree_esp }}
                        </div>
                        <div class="mb-3 col-6">
                            <label for="id_start_date">Fecha de Inicio de Estudios</label>
                            {{ form.start_date }}
                        </div>
                        <div class="mb-3 col-6">
                            <label for="id_finish_date">Fecha de Graduación</label>
                            {{ form.finish_date }}
                        </div>
                        <div class="mb-3 col-6">
                            <label for="id_in_progress">Aún estudio aquí</label>
                            {{ form.in_progress }}
                        </div>
                    
                </section>
            </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-dark" data-bs-dismiss="modal">Cerrar</button>
                    <button type="submit" class="btn btn-success">Guardar Estudios</button>
                </div>
            </form>
            </div>
        </div>
    </div>
    <button onclick="topFunction()" id="go-top" title="Ir arriba">Ir arriba</button>
    <section class="container mt-3">
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
            Agregar Estudios
        </button>
        <div class="row">
            {% for item in object_list %}
                <div class="card border-success mb-3 col-3" >
                    <div class="card-header bg-transparent border-success">
                        {{item.type_degree}} 
                        &nbsp<a href="{% url 'academy-update' pk=item.id %}" title="Modificar"><i class="fa-solid fa-pen-to-square"></i></a>
                        <a href="#" title="Eliminar" id="delbtn" class="place-top-right" data-bs-toggle="modal" data-bs-target="#academyModal" onclick="changeHref({{ item.id }});"><i class="fa-solid fa-file-circle-xmark text-danger"></i></a>
                    </div>
                    <div class="card-body text-success">
                    <h5 class="card-title">{{ item.academy_name }}</h5>
                    <p class="card-text">{{ item.degree_obtained }} - {{ item.degree_esp }}</p>
                    <input type="hidden" id="id-{{ item.id }}" value="{% url 'academy-delete' pk=item.id %}">
                    </div>
                    <div class="card-footer bg-transparent text-center border-success">Graduado desde {{ item.finish_date|date:"Y" }} </div>
                </div>
            {% empty %}
                <p class="text-center">Aún no has registrado tus estudiós. Empecemos!!</p>
            {% endfor %}
        </div>        
    </section>

<div class="modal fade" id="academyModal" tabindex="-1" aria-labelledby="academyModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="academyModalLabel">Eliminar Estudios</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                ¿Está seguro que desea eliminar este estudio?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                <a href="#" id="anchorbtn" class="btn btn-primary">Eliminar</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/datauser/academy_upd_form.html
{% extends 'core/base.html' %}
{% block titulo %}Academia{% endblock %}
{% load static %}

{% block estilo %}
<link rel="stylesheet" href="{% static 'css/custom.css' %}">
{% endblock %}
{% block contenido %}
{% include 'core/menu.html' %}

<section class="container mb-5">
    <h1 class="h3 mt-5 mb-5">Actualizar Registros Académicos</h1>
    <form method="post" class="border p-4 row">
        {% csrf_token %}
        <div class="mb-3 col-6">
            <label for="id_type_degree">Tipo de Educación</label>
            {{ form.type_degree }}
        </div>
        <div class="mb-3 col-6">
            <label for="id_academy_name">Institución Educativa</label>
            {{ form.academy_name }}
        </div>
        <div class="mb-3 col-12">
            <label for="id_degree_obtained">Grado Obtenido</label>
            {{ form.degree_obtained }}
        </div>
        <div class="mb-3 col-12">
            <label for="id_degree_esp">Especialidad del Grado</label>
            {{ form.degree_esp }}
        </div>
        <div class="mb-3 col-6">
            <label for="id_start_date">Fecha de Inicio de Estudios</label>
            {{ form.start_date }}
        </div>
        <div class="mb-3 col-6">
            <label for="id_finish_date">Fecha de Graduación</label>
            {{ form.finish_date }}
        </div>
        <div class="mb-3 col-6">
            <label for="id_in_progress">Aún estudio aquí</label>
            {{ form.in_progress }}
        </div>
        <div class="col-12 mt-3">
            <div class="row justify-content-end">
                <div class="col-3">
                    <a href="{% url 'academy-create' %}" class="btn btn-outline-dark">Cancelar</a>
                </div>
                <div class="col-3">
                    <button type="submit" class="btn btn-success">Actualizar Estudios</button>
                </div>
            </div>
        </div>
    </form>
</section>

{% endblock %}

templates/datauser/history_form.html
{% extends 'core/base.html' %}
{% block titulo %}Historia Laboral{% endblock %}
{% load static %}

{% block estilo %}
{% if object_list %}
<link rel="stylesheet" href="{% static 'css/timeline.css' %}">
{% endif %}
<link rel="stylesheet" href="{% static 'css/custom.css' %}">
{% endblock %}
{% block contenido %}
{% include 'core/menu.html' %}
<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
    aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <form method="post">
                {% csrf_token %}
                <div class="modal-header">
                    <h1 class="modal-title fs-5 h3" id="exampleModalLabel">Agregar historia laboral</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <section class="container mt-3 row">
                        <div class="mb-3 col-6">
                            <label for="id_stack">Tecnologias Usadas</label>
                            {{ form.stack }}
                        </div>
                        <div class="mb-3 col-6">
                            <label for="id_company">Empresa</label>
                            {{ form.company }}
                        </div>
                        <div class="mb-3 col-12">
                            <label for="id_position">Cargo</label>
                            {{ form.position }}
                        </div>
                        <div class="mb-3 col-12 text-center">
                            <label for="id_job_description">Funciones Desempeñadas</label><br>
                            {{ form.job_description }}
                        </div>
                        <div class="mb-3 col-6">
                            <label for="id_start_date">Fecha de Inicio</label>
                            {{ form.start_date }}
                        </div>
                        <div class="mb-3 col-6">
                            <label for="id_end_date">Fecha de Culminación</label>
                            {{ form.end_date }}
                        </div>
                        <div class="mb-3 col-6">
                            <label for="id_still_work">Aún trabajo allí</label>
                            {{ form.still_work }}
                        </div>
                    </section>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-dark" data-bs-dismiss="modal">Cerrar</button>
                    <button type="submit" class="btn btn-success">Guardar Historia</button>
                </div>
            </form>
        </div>
    </div>
</div>
<button onclick="topFunction()" id="go-top" title="Ir arriba">Ir arriba</button>
<section id="timeline-container" class="container mt-3">
    <div class="row">
        <div class="col-12">
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                Agregar Historia Laboral
            </button>
        </div>
    </div>
    <div id="timeline">
    {% for item in object_list %}
        <div class="child">
            <div class="content">
                <h4>
                    <a href="{% url 'history-update' pk=item.id %}" title="Modificar"><i class="fa-solid fa-pen-to-square"></i></a>
                    {{ item.start_date| date:"Y" }} - 
                    {% if item.end_date %} 
                        {{ item.end_date| date:"Y" }}
                    {% else %}
                        Actualmente
                    {% endif %}
                    &nbsp
                </h4>
                <p>{{ item.company }} - {{ item.position }}</p>
                <p>{{ item.job_description|safe }}</p>
                <input type="hidden" id="id-{{ item.id }}" value="{% url 'history-delete' pk=item.id %}">
                <div><a href="#" title="Eliminar" id="delbtn" class="place-top-right" data-bs-toggle="modal" data-bs-target="#historyModal" onclick="changeHref({{ item.id }});"><i class="fa-solid fa-file-circle-xmark text-danger"></i></a></div>
            </div>
        </div>
    {% empty %}
    <p class="text-center">Aún no has registrado tu historia laboral. Empecemos!!</p>
    {% endfor %}
    </div>
</section>

<div class="modal fade" id="historyModal" tabindex="-1" aria-labelledby="historyModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="historyModalLabel">Eliminar historia laboral</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                ¿Está seguro que desea eliminar esta historia laboral?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                <a href="#" id="anchorbtn" class="btn btn-primary">Eliminar</a>
            </div>
        </div>
    </div>
</div>

<script src="{% static 'js/timeline.js' %}"></script>
{% endblock %}

templates/datauser/history_upd_form.html
{% extends 'core/base.html' %}
{% block titulo %}Historia Laboral{% endblock %}
{% load static %}

{% block estilo %}
<link rel="stylesheet" href="{% static 'css/custom.css' %}">
{% endblock %}
{% block contenido %}
{% include 'core/menu.html' %}

<section class="container mb-5">
    <h1 class="h3 mt-5 mb-5">Actualizar historia laboral</h1>
    <form method="post" class="border p-4 row">
        {% csrf_token %}
        <div class="mb-3 col-6">
            <label for="id_stack">Tecnologias Usadas</label>
            {{ form.stack }}
        </div>
        <div class="mb-3 col-6">
            <label for="id_company">Empresa</label>
            {{ form.company }}
        </div>
        <div class="mb-3 col-12">
            <label for="id_position">Cargo</label>
            {{ form.position }}
        </div>
        <div class="mb-3 col-12 text-center">
            <label for="id_job_description">Funciones Desempeñadas</label><br>
            {{ form.job_description }}
        </div>
        <div class="mb-3 col-6">
            <label for="id_start_date">Fecha de Inicio</label>
            {{ form.start_date }}
        </div>
        <div class="mb-3 col-6">
            <label for="id_end_date">Fecha de Culminación</label>
            {{ form.end_date }}
        </div>
        <div class="mb-3 col-6">
            <label for="id_still_work">Aún trabajo allí</label>
            {{ form.still_work }}
        </div>
        <div class="col-12 mt-3">
            <div class="row justify-content-end">
                <div class="col-3">
                    <a href="{% url 'history-create' %}" class="btn btn-outline-dark">Cancelar</a>
                </div>
                <div class="col-3">
                    <button type="submit" class="btn btn-success">Actualizar historia</button>
                </div>
            </div>
        </div>
    </form>
</section>

{% endblock %}

templates/datauser/project_form.html
{% extends 'core/base.html' %}
{% block titulo %}Proyectos{% endblock %}
{% load static %}

{% block estilo %}
<link rel="stylesheet" href="{% static 'css/custom.css' %}">
{% endblock %}
{% block contenido %}
{% include 'core/menu.html' %}
<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
    aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <form method="post">
                {% csrf_token %}
                <div class="modal-header">
                    <h1 class="modal-title fs-5 h3" id="exampleModalLabel">Agregar proyectos desarrollados</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <section class="container mt-3 row">
                        <div class="mb-3 col-6">
                            <label for="id_stack">Tecnologias Usadas</label>
                            {{ form.stack }}
                        </div>
                        <div class="mb-3 col-6">
                            <label for="id_name_project">Nombre de Proyecto</label>
                            {{ form.name_project }}
                        </div>
                        <div class="mb-3 col-12">
                            <label for="id_resume_project">Descripcion</label>
                            {{ form.resume_project }}
                        </div>
                        <div class="mb-3 col-6">
                            <label for="id_url_repo">Url Repositorio</label>
                            {{ form.url_repo }}
                        </div>
                        <div class="mb-3 col-6">
                            <label for="id_year_production">Año en Producción</label>
                            {{ form.year_production }}
                        </div>
                        <div class="mb-3 col-6">
                            <label for="id_developing">Aún en desarrollo</label>
                            {{ form.developing }}
                        </div>
                    </section>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-dark" data-bs-dismiss="modal">Cerrar</button>
                    <button type="submit" class="btn btn-success">Guardar Proyecto</button>
                </div>
            </form>
        </div>
    </div>
</div>
<button onclick="topFunction()" id="go-top" title="Ir arriba">Ir arriba</button>
<section class="container mt-3">
    <div class="row">
        <div class="col-12">
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                Agregar Proyecto
            </button>
        </div>
        {% for item in object_list %}
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">
                        {{ item.name_project }}: {{ item.year_production }}
                        &nbsp<a href="{% url 'project-update' pk=item.id %}" title="Modificar"><i class="fa-solid fa-pen-to-square"></i></a>
                        <a href="#" title="Eliminar" id="delbtn" class="place-top-right" data-bs-toggle="modal" data-bs-target="#projectModal" onclick="changeHref({{ item.id }});"><i class="fa-solid fa-file-circle-xmark text-danger"></i></a>
                    </h5>
                    <p class="card-text">{{ item.resume_project }}</p>
                    <a href="{{ item.url_repo }}" class="btn btn-primary">Url Repositorio</a>
                    <input type="hidden" id="id-{{ item.id }}" value="{% url 'project-delete' pk=item.id %}">
                </div>
                <div class="card-footer">
                    <small class="text-body-secondary">
                        {% for stack in item.stack.all %}
                        {{ stack.name_stack }} - 
                        {% endfor %}
                    </small>
                </div>
            </div>
        {% empty %}
        <p class="text-center">Aún no has registrado tu proyectos desarrollados. Empecemos!!</p>
        {% endfor %}
    </div>
</section>

<div class="modal fade" id="projectModal" tabindex="-1" aria-labelledby="projectModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="projectModalLabel">Eliminar Proyecto</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                ¿Está seguro que desea eliminar este proyecto?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                <a href="#" id="anchorbtn" class="btn btn-primary">Eliminar</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}